# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Glynn admin
name: Disjfa valours
email: disjfa@disjfa.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/glynn-admin" # the subpath of your site, e.g. /blog
url: "https://disjfa.github.io" # the base hostname & protocol for your site
github_url:  https://github.com/disjfa/glynn-admin
github_username:  disjfa

google_analytics: UA-81188701-1

# Build settings
markdown: kramdown

# deployment
host: 0.0.0.0
port: 5000

exclude:
  - node_modules