# Site settings
title: Glynn admin
name: Disjfa valours
email: disjfa@disjfa.com
description: >
  A simple admin page, responsive and beautiful. For useage on your own product.
  I has a lot of example use cases you can implement on your own site or admin page.
baseurl: "/glynn-admin"
url: "https://disjfa.github.io"
github_url:  https://github.com/disjfa/glynn-admin
github_username:  disjfa

# Google
google_analytics: UA-81188701-1

# Build settings
markdown: kramdown

# deployment
source: site
host: 0.0.0.0
port: 5000
